name: Update War Monitor

on:
  workflow_dispatch:
  schedule:
    - cron: "*/15 * * * *"  # runs every 15 minutes

jobs:
  run-news-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run War Monitor Script
        run: python update_news.py
