name: Update War Monitor

on:
  schedule:
    - cron: "*/15 * * * *"  # Runs every 15 minutes
  workflow_dispatch:        # Allows manual run

jobs:
  run-news-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install feedparser pytz

      - name: Run bot
        run: python update_news.py

      - name: Commit & push updated data
        run: |
          git config --global user.name "WarBot"
          git config --global user.email "warbot@example.com"
          git add war_monitor_data.json
          git commit -m "Update war data feed"
          git push
